from __future__ import annotations

import argparse
import json
import math
import pickle
import shutil
import sys
import types
from pathlib import Path
from typing import Any

from main_train_score_proex_upstream_adapter import (
    _build_user_profile,
    _candidate_groups,
    _checkpoint_config_summary,
    _import_runtime,
    _load_interactions,
    _load_item_embeddings,
    _make_sparse_mats,
    _normalize_adj,
    _pushd,
    _read_csv,
    _resolve_device,
    _sample_negatives,
    _sanitize_dataset_name,
    _set_seed,
    _text,
    _write_csv,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Train pinned upstream ProRec LightGCN_promax on a same-candidate "
            "adapter package and emit exact candidate scores."
        )
    )
    parser.add_argument("--adapter_dir", required=True)
    parser.add_argument("--prorec_repo_dir", required=True)
    parser.add_argument("--output_scores_path", default=None)
    parser.add_argument("--checkpoint_path", default=None)
    parser.add_argument("--dataset_name", default="")
    parser.add_argument("--epochs", type=int, default=3000)
    parser.add_argument("--batch_size", type=int, default=4096)
    parser.add_argument("--lr", type=float, default=1.0e-3)
    parser.add_argument("--weight_decay", type=float, default=0.0)
    parser.add_argument("--embedding_size", type=int, default=32)
    parser.add_argument("--layer_num", type=int, default=3)
    parser.add_argument("--reg_weight", type=float, default=1.0e-6)
    parser.add_argument("--sdr_weight", type=float, default=1.5)
    parser.add_argument("--s2dr_weight", type=float, default=0.05)
    parser.add_argument("--keep_rate", type=float, default=1.0)
    parser.add_argument("--rag_topk", type=int, default=20)
    parser.add_argument("--rag_block_users", type=int, default=128)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--seed", type=int, default=2025)
    parser.add_argument("--log_every", type=int, default=10)
    return parser.parse_args()


def _l2_normalize(matrix: Any, np: Any) -> Any:
    denom = np.linalg.norm(matrix, axis=1, keepdims=True)
    return (matrix / np.maximum(denom, 1.0e-8)).astype(np.float32)


def _make_profile_retrieval_mat(
    *,
    user_profiles: Any,
    item_profiles: Any,
    train_sequences: dict[int, list[int]],
    user_count: int,
    item_count: int,
    topk: int,
    block_users: int,
    coo_matrix: Any,
    np: Any,
) -> tuple[Any, dict[str, Any]]:
    topk = max(1, int(topk))
    block_users = max(1, int(block_users))
    item_norm = _l2_normalize(item_profiles, np)
    user_norm = _l2_normalize(user_profiles, np)
    rows: list[int] = []
    cols: list[int] = []
    for start in range(0, user_count, block_users):
        end = min(start + block_users, user_count)
        sims = user_norm[start:end] @ item_norm.T
        for offset, scores in enumerate(sims):
            user_idx = start + offset
            seen = train_sequences.get(user_idx, [])
            if seen:
                valid_seen = [idx for idx in seen if 0 <= idx < item_count]
                scores[valid_seen] = -np.inf
            if topk >= item_count:
                picked = np.argsort(-scores)
            else:
                candidate = np.argpartition(-scores, topk - 1)[:topk]
                picked = candidate[np.argsort(-scores[candidate])]
            for item_idx in picked[:topk]:
                if np.isfinite(scores[item_idx]):
                    rows.append(user_idx)
                    cols.append(int(item_idx))
    data = np.ones((len(rows),), dtype=np.float32)
    mat = coo_matrix((data, (rows, cols)), shape=(user_count, item_count), dtype=np.float32)
    summary = {
        "profile_retrieval_bridge": "qwen3_pca64_user_item_profile_topk_latent_interactions",
        "rag_topk": topk,
        "rag_block_users": block_users,
        "latent_interaction_edges": int(len(rows)),
        "latent_interaction_users": int(len(set(rows))),
        "latent_interaction_items": int(len(set(cols))),
        "note": (
            "ProMax's official LightGCN_promax objective is preserved. The required "
            "new_trn_rag_mat.pkl is generated by Qwen3-derived PCA64 user-profile to "
            "item-profile retrieval over the same-candidate domain, excluding observed "
            "training interactions."
        ),
    }
    return mat, summary


def _write_profile_data(
    *,
    adapter_dir: Path,
    repo_dir: Path,
    dataset_name: str,
    trn_mat: Any,
    val_mat: Any,
    tst_mat: Any,
    new_trn_rag_mat: Any,
    user_profiles: Any,
    item_profiles: Any,
    item_embedding_source_path: Path,
    manifest: dict[str, Any],
) -> tuple[Path, Path]:
    handled_dir = adapter_dir / "promax" / "handled"
    handled_dir.mkdir(parents=True, exist_ok=True)
    for name, payload in {
        "trn_mat.pkl": trn_mat,
        "val_mat.pkl": val_mat,
        "tst_mat.pkl": tst_mat,
        "new_trn_rag_mat.pkl": new_trn_rag_mat,
        "usr_emb_np.pkl": user_profiles,
        "itm_emb_np.pkl": item_profiles,
    }.items():
        with (handled_dir / name).open("wb") as fh:
            pickle.dump(payload, fh)

    manifest = {
        **manifest,
        "adapter_profile_dir": str(handled_dir),
        "item_embedding_source_path": str(item_embedding_source_path),
        "user_profile_shape": list(user_profiles.shape),
        "item_profile_shape": list(item_profiles.shape),
    }
    (handled_dir / "promax_profile_bridge_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    official_data_dir = repo_dir / "data" / dataset_name
    if official_data_dir.exists() or official_data_dir.is_symlink():
        resolved = official_data_dir.resolve() if official_data_dir.exists() else official_data_dir
        if repo_dir.resolve() not in resolved.parents and resolved != handled_dir.resolve():
            raise RuntimeError(f"Refusing to replace unexpected ProRec data directory: {official_data_dir}")
        if official_data_dir.is_symlink() or official_data_dir.is_file():
            official_data_dir.unlink()
        else:
            shutil.rmtree(official_data_dir)
    official_data_dir.parent.mkdir(parents=True, exist_ok=True)
    try:
        official_data_dir.symlink_to(handled_dir.resolve(), target_is_directory=True)
    except Exception:
        shutil.copytree(handled_dir, official_data_dir)
    return handled_dir, official_data_dir


def _make_torch_adj_from_user_item_mat(
    mat: Any,
    *,
    user_count: int,
    item_count: int,
    sp: Any,
    np: Any,
    torch: Any,
    device: Any,
) -> Any:
    a = sp.csr_matrix((user_count, user_count))
    b = sp.csr_matrix((item_count, item_count))
    adj = sp.vstack([sp.hstack([a, mat]), sp.hstack([mat.transpose(), b])])
    adj = (adj != 0) * 1.0
    adj = _normalize_adj(adj, sp, np)
    idxs = torch.from_numpy(np.vstack([adj.row, adj.col]).astype(np.int64))
    vals = torch.from_numpy(adj.data.astype(np.float32))
    shape = torch.Size(adj.shape)
    return torch.sparse_coo_tensor(idxs, vals, shape).coalesce().to(device)


class _DataHandler:
    def __init__(self, *, torch_adj: Any, user_count: int, item_count: int, sp: Any, np: Any, torch: Any, device: Any) -> None:
        self.torch_adj = torch_adj
        self.user_count = user_count
        self.item_count = item_count
        self.sp = sp
        self.np = np
        self.torch = torch
        self.device = device

    def _make_torch_adj(self, mat: Any) -> Any:
        return _make_torch_adj_from_user_item_mat(
            mat,
            user_count=self.user_count,
            item_count=self.item_count,
            sp=self.sp,
            np=self.np,
            torch=self.torch,
            device=self.device,
        )


def _official_configs(
    args: argparse.Namespace,
    *,
    dataset_name: str,
    user_count: int,
    item_count: int,
    user_profiles: Any,
    item_profiles: Any,
    device: Any,
) -> dict[str, Any]:
    hyper = {
        "layer_num": args.layer_num,
        "reg_weight": args.reg_weight,
        "sdr_weight": args.sdr_weight,
        "s2dr_weight": args.s2dr_weight,
    }
    return {
        "device": str(device),
        "usrprf_embeds": user_profiles,
        "itmprf_embeds": item_profiles,
        "optimizer": {"name": "adam", "lr": args.lr, "weight_decay": args.weight_decay},
        "train": {
            "epoch": args.epochs,
            "batch_size": args.batch_size,
            "save_model": True,
            "loss": "pairwise",
            "test_step": 3,
            "reproducible": True,
            "seed": args.seed,
            "patience": 20,
            "log_loss": False,
        },
        "test": {"metrics": ["recall", "ndcg"], "k": [5, 10, 20], "batch_size": 1024},
        "data": {"type": "general_cf", "name": dataset_name, "user_num": user_count, "item_num": item_count},
        "model": {
            "name": "lightgcn_promax",
            "type": "discriminative",
            "keep_rate": args.keep_rate,
            "embedding_size": args.embedding_size,
            dataset_name: hyper,
            **hyper,
        },
        "tune": {"enable": False},
    }


def _import_official_model(repo_dir: Path, configs: dict[str, Any]) -> Any:
    encoder_dir = repo_dir / "encoder"
    if not encoder_dir.exists():
        raise FileNotFoundError(f"ProRec encoder directory not found: {encoder_dir}")
    for name in list(sys.modules):
        if name == "config" or name.startswith("config.") or name.startswith("models."):
            del sys.modules[name]
    config_pkg = types.ModuleType("config")
    config_pkg.__path__ = [str(encoder_dir / "config")]
    config_mod = types.ModuleType("config.configurator")
    config_mod.configs = configs
    sys.modules["config"] = config_pkg
    sys.modules["config.configurator"] = config_mod
    sys.path.insert(0, str(encoder_dir))
    module = __import__("models.general_cf.lightgcn_promax", fromlist=["LightGCN_promax"])
    return getattr(module, "LightGCN_promax")


def _train_official_model(
    *,
    model: Any,
    train_pairs: list[tuple[int, int]],
    positives: dict[int, set[int]],
    item_count: int,
    args: argparse.Namespace,
    torch: Any,
    DataLoader: Any,
    TensorDataset: Any,
    Adam: Any,
    device: Any,
) -> list[dict[str, Any]]:
    user_tensor = torch.tensor([u for u, _ in train_pairs], dtype=torch.long)
    item_tensor = torch.tensor([i for _, i in train_pairs], dtype=torch.long)
    dataset = TensorDataset(user_tensor, item_tensor)
    generator = torch.Generator()
    generator.manual_seed(args.seed)
    loader = DataLoader(dataset, batch_size=args.batch_size, shuffle=True, generator=generator)
    optimizer = Adam(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    import random

    rng = random.Random(args.seed)
    logs: list[dict[str, Any]] = []
    for epoch in range(1, args.epochs + 1):
        model.train()
        total_loss = 0.0
        steps = 0
        for users, pos_items in loader:
            users = users.to(device)
            pos_items = pos_items.to(device)
            neg_items = torch.tensor(
                _sample_negatives(users.detach().cpu().tolist(), positives=positives, item_count=item_count, rng=rng),
                dtype=torch.long,
                device=device,
            )
            optimizer.zero_grad(set_to_none=True)
            loss, _losses = model.cal_loss([users, pos_items, neg_items])
            loss.backward()
            optimizer.step()
            if hasattr(model, "final_embeds"):
                model.final_embeds = None
            total_loss += float(loss.detach().cpu())
            steps += 1
        row = {"epoch": epoch, "train_loss": total_loss / max(steps, 1)}
        logs.append(row)
        if args.log_every > 0 and (epoch == 1 or epoch == args.epochs or epoch % args.log_every == 0):
            print(f"[promax-official] epoch={epoch} train_loss={row['train_loss']:.6f}", flush=True)
    return logs


def _score_candidates(
    *,
    model: Any,
    candidate_events: list[dict[str, Any]],
    output_scores_path: Path,
    torch: Any,
) -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    model.eval()
    with torch.no_grad():
        if hasattr(model, "is_training"):
            model.is_training = False
        user_embeds, item_embeds = model.forward(model.adj, 1.0)
        for event in candidate_events:
            user_idx = int(event["proex_user_idx"])
            candidate_indices = [int(row["proex_item_idx"]) for row in event["candidate_rows"]]
            item_tensor = torch.tensor(candidate_indices, dtype=torch.long, device=item_embeds.device)
            scores = item_embeds.index_select(0, item_tensor).matmul(user_embeds[user_idx])
            if not torch.isfinite(scores).all():
                raise RuntimeError(f"Non-finite ProMax score for source_event_id={event['source_event_id']}")
            for row, score in zip(event["candidate_rows"], scores.detach().cpu().tolist()):
                rows.append(
                    {
                        "source_event_id": event["source_event_id"],
                        "user_id": event["user_id"],
                        "item_id": row["item_id"],
                        "score": float(score),
                    }
                )
    _write_csv(rows, output_scores_path, ["source_event_id", "user_id", "item_id", "score"])
    candidate_rows = sum(len(event["candidate_rows"]) for event in candidate_events)
    return {
        "candidate_events": len(candidate_events),
        "candidate_rows": candidate_rows,
        "scored_rows": len(rows),
        "score_coverage_rate": float(len(rows) / candidate_rows) if candidate_rows else 0.0,
        "output_scores_path": str(output_scores_path),
    }


def train_and_score(args: argparse.Namespace) -> dict[str, Any]:
    np, sp, torch, coo_matrix, DataLoader, TensorDataset, Adam = _import_runtime()
    _set_seed(args.seed, torch, np)
    adapter_dir = Path(args.adapter_dir).expanduser().resolve()
    repo_dir = Path(args.prorec_repo_dir).expanduser().resolve()
    metadata = json.loads((adapter_dir / "adapter_metadata.json").read_text(encoding="utf-8"))
    user_count = int(metadata.get("users", 0))
    item_count = int(metadata.get("items", 0))
    dataset_name = _sanitize_dataset_name(args.dataset_name or f"pony_promax_{adapter_dir.name}")
    output_scores_path = Path(args.output_scores_path).expanduser().resolve() if args.output_scores_path else adapter_dir / "promax_official_scores.csv"
    checkpoint_path = Path(args.checkpoint_path).expanduser().resolve() if args.checkpoint_path else adapter_dir / "promax_official_model.pt"

    sequences = _load_interactions(adapter_dir / "llm_esr" / "handled" / "inter.txt")
    item_profile, item_embedding_source_path, item_embedding_metadata = _load_item_embeddings(adapter_dir, np)
    if item_profile.shape[0] != item_count:
        raise ValueError(f"item embeddings rows={item_profile.shape[0]} but adapter metadata items={item_count}")
    user_profile, missing_users = _build_user_profile(sequences=sequences, item_profile=item_profile, user_count=user_count, np=np)
    trn_mat, val_mat, tst_mat, train_pairs = _make_sparse_mats(
        sequences=sequences,
        user_count=user_count,
        item_count=item_count,
        coo_matrix=coo_matrix,
    )
    new_trn_rag_mat, rag_manifest = _make_profile_retrieval_mat(
        user_profiles=user_profile,
        item_profiles=item_profile,
        train_sequences=sequences,
        user_count=user_count,
        item_count=item_count,
        topk=int(args.rag_topk),
        block_users=int(args.rag_block_users),
        coo_matrix=coo_matrix,
        np=np,
    )
    positives: dict[int, set[int]] = {}
    for user_idx, item_idx in train_pairs:
        positives.setdefault(user_idx, set()).add(item_idx)
    profile_manifest = {
        **item_embedding_metadata,
        **rag_manifest,
        "user_profile_source": "train_history_mean_of_qwen3_profile_item_embeddings",
        "missing_base_history_users": int(missing_users),
        "item_embedding_dim": int(item_profile.shape[1]),
    }
    handled_dir, official_data_dir = _write_profile_data(
        adapter_dir=adapter_dir,
        repo_dir=repo_dir,
        dataset_name=dataset_name,
        trn_mat=trn_mat,
        val_mat=val_mat,
        tst_mat=tst_mat,
        new_trn_rag_mat=new_trn_rag_mat,
        user_profiles=user_profile,
        item_profiles=item_profile,
        item_embedding_source_path=item_embedding_source_path,
        manifest=profile_manifest,
    )
    profile_manifest_path = handled_dir / "promax_profile_bridge_manifest.json"
    device = _resolve_device(args.device, torch)
    if device.type != "cuda":
        raise RuntimeError("Pinned ProMax LightGCN_promax calls .cuda(); run this official adapter on a CUDA device.")
    torch_adj = _make_torch_adj_from_user_item_mat(trn_mat, user_count=user_count, item_count=item_count, sp=sp, np=np, torch=torch, device=device)
    data_handler = _DataHandler(torch_adj=torch_adj, user_count=user_count, item_count=item_count, sp=sp, np=np, torch=torch, device=device)
    configs = _official_configs(
        args,
        dataset_name=dataset_name,
        user_count=user_count,
        item_count=item_count,
        user_profiles=user_profile,
        item_profiles=item_profile,
        device=device,
    )
    LightGCNProMax = _import_official_model(repo_dir, configs)
    with _pushd(repo_dir / "encoder"):
        model = LightGCNProMax(data_handler).to(device)
        logs = _train_official_model(
            model=model,
            train_pairs=train_pairs,
            positives=positives,
            item_count=item_count,
            args=args,
            torch=torch,
            DataLoader=DataLoader,
            TensorDataset=TensorDataset,
            Adam=Adam,
            device=device,
        )
        score_summary = _score_candidates(
            model=model,
            candidate_events=_candidate_groups(adapter_dir / "candidate_items_mapped.csv"),
            output_scores_path=output_scores_path,
            torch=torch,
        )
        checkpoint_path.parent.mkdir(parents=True, exist_ok=True)
        torch.save(
            {
                "state_dict": model.state_dict(),
                "args": vars(args),
                "configs": _checkpoint_config_summary(configs, profile_manifest_path=profile_manifest_path),
                "summary": score_summary,
            },
            checkpoint_path,
            pickle_protocol=4,
        )

    trainable_params = sum(param.numel() for param in model.parameters() if param.requires_grad)
    summary = {
        "adapter_dir": str(adapter_dir),
        "baseline_name": "promax_official_qwen3base_profile",
        "artifact_class": "official_promax_same_candidate_score",
        "official_result_gate": "provenance_coverage_and_import_required",
        "upstream_repo": "https://github.com/BlueGhostYi/ProRec",
        "official_model_class": "encoder.models.general_cf.lightgcn_promax.LightGCN_promax",
        "users": user_count,
        "items": item_count,
        "train_edges": len(train_pairs),
        "epochs": args.epochs,
        "batch_size": args.batch_size,
        "lr": args.lr,
        "embedding_size": args.embedding_size,
        "layer_num": args.layer_num,
        "sdr_weight": args.sdr_weight,
        "s2dr_weight": args.s2dr_weight,
        "device": str(device),
        "seed": args.seed,
        "trainable_params": trainable_params,
        "final_train_loss": logs[-1]["train_loss"] if logs else math.nan,
        "official_data_dir": str(official_data_dir),
        "adapter_profile_dir": str(handled_dir),
        "profile_bridge_manifest_path": str(profile_manifest_path),
        "checkpoint_path": str(checkpoint_path),
        "checkpoint_storage_decision": "profile_arrays_and_rag_graph_externalized_and_manifest_recorded",
        **profile_manifest,
        **score_summary,
        "note": (
            "Scores use pinned ProRec LightGCN_promax with official BPR, SDR, "
            "and S2DR losses. Local code supplies same-candidate graph data, "
            "Qwen3-derived profile arrays, Qwen3 retrieval latent interactions, "
            "and exact candidate-score export."
        ),
    }
    _write_csv([summary], adapter_dir / "promax_upstream_score_summary.csv", list(summary.keys()))
    _write_csv(logs, adapter_dir / "promax_upstream_epoch_log.csv", ["epoch", "train_loss"])
    (adapter_dir / "promax_upstream_score_metadata.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return summary


def main() -> None:
    summary = train_and_score(parse_args())
    for key, value in summary.items():
        print(f"{key}={value}", flush=True)


if __name__ == "__main__":
    main()
